# -*- coding: utf-8 -*-
"""C108 PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kQFq3C33ROIOAVeT-Yi1T3vIOat2bVly
"""

import csv
import plotly.figure_factory as ff
import pandas as pd

from google.colab import files
data_to_load = files.upload()

df = pd.read_csv("C108 Project Data.csv")
fig = ff.create_distplot([df["Avg Rating"].tolist()], ["Rating"], show_hist = True)
fig.show()